simulation_timestep: 0.00416666666  # simulation settings
simulation_use_gui: False
simulation_action_steps: 300
realtime: False

plane_position: [ 0, 0, 0 ]  # plane settings
plane_quaternion: [ 0, 0, 0, 1 ]

pusher_radius: 0.7 # pusher settings
pusher_height: 0.1
pusher_link_mass: 0.5
pusher_lin_vel: 1.0

object_position: [ 0, 0, 0.2 ] # object settings
object_quaternion: [ 0, 0, 0, 1 ]
object_size_mean: 0.5
object_size_sigma: 0.2
object_mass_mean: 1.0
object_mass_sigma: 0.9
object_friction_mean: 1.0
object_friction_sigma: 0.8
object_restitution_mean: 1.0
object_restitution_sigma: 0.9
object_spring_stiffness_mean: 200.0
object_spring_stiffness_sigma: 190.0
object_elastic_stiffness_mean: 200.0
object_elastic_stiffness_sigma: 190.0

cam_target_pos: [ 0, 0.3, 0.1 ]  # camera settings
cam_roll: 0
cam_pitch: 0
cam_yaw: 0
cam_distance: 1.5
projection_w: 640
projection_h: 480
near_plane: 0.01
far_plane: 100
fov: 60

num_outputs: 4 # haptic regression network
batch_size: 30
action_kernel_size: 3
dropout: 0.8
lstm_units: 32